site_name: ArteNaMão

nav:
  - Home: index.md
  - Visão do produto e projeto:
      - Visão geral do produto: visao-produto-projeto/visao-produto.md
      - Visão geral do projeto: visao-produto-projeto/visao-projeto.md
      - Processo de desenvolvimento de software: visao-produto-projeto/processo-de-desenvolvimento-de-software.md
  - Backlog do Produto: backlog-do-produto/backlog-do-produto.md
  - Entregas:
      - Unidade 1: entregas/unidade-1.md
      - Unidade 2: entregas/unidade-2.md
      - Unidade 3: entregas/unidade-3.md
  - Lições Aprendidas: licoes/unidade-2.md
repo_url: https://github.com/mdsreq-fga-unb/2023.2-ArteNaMao
repo_name: ArteNaMao
theme:
  name: material
  language: pt
  favicon: assets/pincel.png
  logo: assets/pincel.png
  usm: docs/assets/User-Story-Map-Framework-_1_.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra_css:
 
extra:
  generator: false
